namespace DChess.Core.Game;

public static class NamedSquare
{
    // ReSharper disable InconsistentNaming
    // ReSharper disable UnusedMember.Global
    public static readonly Square NullSquare = new(255);
    public static readonly Square a1 = new('a', 1);
    public static readonly Square a2 = new('a', 2);
    public static readonly Square a3 = new('a', 3);
    public static readonly Square a4 = new('a', 4);
    public static readonly Square a5 = new('a', 5);
    public static readonly Square a6 = new('a', 6);
    public static readonly Square a7 = new('a', 7);
    public static readonly Square a8 = new('a', 8);
    public static readonly Square b1 = new('b', 1);
    public static readonly Square b2 = new('b', 2);
    public static readonly Square b3 = new('b', 3);
    public static readonly Square b4 = new('b', 4);
    public static readonly Square b5 = new('b', 5);
    public static readonly Square b6 = new('b', 6);
    public static readonly Square b7 = new('b', 7);
    public static readonly Square b8 = new('b', 8);
    public static readonly Square c1 = new('c', 1);
    public static readonly Square c2 = new('c', 2);
    public static readonly Square c3 = new('c', 3);
    public static readonly Square c4 = new('c', 4);
    public static readonly Square c5 = new('c', 5);
    public static readonly Square c6 = new('c', 6);
    public static readonly Square c7 = new('c', 7);
    public static readonly Square c8 = new('c', 8);
    public static readonly Square d1 = new('d', 1);
    public static readonly Square d2 = new('d', 2);
    public static readonly Square d3 = new('d', 3);
    public static readonly Square d4 = new('d', 4);
    public static readonly Square d5 = new('d', 5);
    public static readonly Square d6 = new('d', 6);
    public static readonly Square d7 = new('d', 7);
    public static readonly Square d8 = new('d', 8);
    public static readonly Square e1 = new('e', 1);
    public static readonly Square e2 = new('e', 2);
    public static readonly Square e3 = new('e', 3);
    public static readonly Square e4 = new('e', 4);
    public static readonly Square e5 = new('e', 5);
    public static readonly Square e6 = new('e', 6);
    public static readonly Square e7 = new('e', 7);
    public static readonly Square e8 = new('e', 8);
    public static readonly Square f1 = new('f', 1);
    public static readonly Square f2 = new('f', 2);
    public static readonly Square f3 = new('f', 3);
    public static readonly Square f4 = new('f', 4);
    public static readonly Square f5 = new('f', 5);
    public static readonly Square f6 = new('f', 6);
    public static readonly Square f7 = new('f', 7);
    public static readonly Square f8 = new('f', 8);
    public static readonly Square g1 = new('g', 1);
    public static readonly Square g2 = new('g', 2);
    public static readonly Square g3 = new('g', 3);
    public static readonly Square g4 = new('g', 4);
    public static readonly Square g5 = new('g', 5);
    public static readonly Square g6 = new('g', 6);
    public static readonly Square g7 = new('g', 7);
    public static readonly Square g8 = new('g', 8);
    public static readonly Square h1 = new('h', 1);
    public static readonly Square h2 = new('h', 2);
    public static readonly Square h3 = new('h', 3);
    public static readonly Square h4 = new('h', 4);
    public static readonly Square h5 = new('h', 5);
    public static readonly Square h6 = new('h', 6);
    public static readonly Square h7 = new('h', 7);
    public static readonly Square h8 = new('h', 8);
}